### ISSUE TITLE
Skips frames and samples frequently - The sound and the picture are not smooth.

### ISSUE THREAD

**Issue by guoluming** [unosquare/ffmediaelement#75] opened 2017-09-11 08:25 UTC
hi,
      There are some problems with normal video playback. Frames and Samples skipping frequently,Both local and online videos can have this problem，The sound and the picture are not smooth.

 Warning - SYNC AUDIO: LATENCY:     -0.283 | WAIT (samples being rendered too early)
     Debug - SYNC-BUFFER: Started.
     Debug - SYNC-BUFFER: Finished. Clock set to    361.135
     Debug - VideoRenderer: Frame skipped at 00:06:01.2000000
     Debug - SYNC-BUFFER: Started.
     Debug - SYNC-BUFFER: Finished. Clock set to    362.080
     Debug - VideoRenderer: Frame skipped at 00:06:02.0800000
     Debug - SYNC-BUFFER: Started.
     Debug - SYNC-BUFFER: Finished. Clock set to    363.400
   Warning - SYNC AUDIO: LATENCY:     -0.297 | WAIT (samples being rendered too early)
     Debug - VideoRenderer: Frame skipped at 00:06:03.7200000
   Warning - SYNC AUDIO: LATENCY:     -0.201 | WAIT (samples being rendered too early)
     Debug - VideoRenderer: Frame skipped at 00:06:05.1200000
     Debug - SYNC-BUFFER: Started.
     Debug - SYNC-BUFFER: Finished. Clock set to    365.442
     Debug - SYNC-BUFFER: Started.
     Debug - SYNC-BUFFER: Finished. Clock set to    365.640
     Debug - VideoRenderer: Frame skipped at 00:06:05.8800000
     Debug - VideoRenderer: Frame skipped at 00:06:06
     Debug - VideoRenderer: Frame skipped at 00:06:06.1600000
     Debug - SYNC-BUFFER: Started.
     Debug - SYNC-BUFFER: Finished. Clock set to    366.400
   Warning - SYNC AUDIO: LATENCY:     -0.341 | WAIT (samples being rendered too early)
   Warning - SYNC AUDIO: LATENCY:     -0.240 | WAIT (samples being rendered too early)

**Comment by mariodivece** [comment] 2017-09-11 13:10
I don't see this problem. You need to provide me with some sample files.

**Comment by StevenGilligan** [comment] 2017-09-11 14:29
I have the same issue, seems to be an environment issue because I tested on my desktop pc (win 7) and it's stuttering a lot, while on my laptop (win 10) with worse cpu and gpu, it's playing with no issues.

The file I used to test is http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_720p_h264.mov but it doesn't matter while video I play, I tested 5-6 videos and they all had constant stuttering.

Here's logs from my test on the pc with issues : https://pastebin.com/EeD1NM7Z 

I'm running windows 7 sp1 64 bits, quad core 3.4 ghz, 8gb RAM,

**Comment by guoluming** [comment] 2017-09-12 02:31
http://mpv.videocc.net/68040382d0/c/68040382d06f36b6ee7a8a0401cc5c4c_1.mp4

**Comment by guoluming** [comment] 2017-09-12 02:35
http://mpv.videocc.net/68040382d0/c/68040382d06f36b6ee7a8a0401cc5c4c_1.mp4
That's the problem with this sample,I tested on my desktop pc (win 7)  ThinkPad T430

**Comment by lyapple2008** [comment] 2017-09-12 02:37
I also have this issue. When I increase the threshold of the audio latency, the sample skip did not happen frequently in audio render. But the frames still skip frequently in video render.

**Comment by mariodivece** [comment] 2017-09-12 04:53
Geez this looks like a Windows 7 issue. I do not have windows 7 installed but I can probably get it on a VM and debug the issue. Can someone troubleshoot and propose a pull request? Another thing that can be tries is to increase the size of the blocks. Find the Blocks dictionary and upon instantiation increase the size of the blocks say 32 for video frames and 128 for audio frames. Could someone try that?

**Comment by guoluming** [comment] 2017-09-12 06:30
modify value in MaxBlocks like  this?  still exists
// TODO: Make this configurable
        internal static readonly Dictionary<MediaType, int> MaxBlocks = new Dictionary<MediaType, int>
        {
            { MediaType.Video, 32 },
            { MediaType.Audio, 128 },
            { MediaType.Subtitle, 120 }
        };

    Debug - VideoRenderer: Frame skipped at 00:03:53.7200000
     Debug - VideoRenderer: Frame skipped at 00:03:55.0800000
     Debug - VideoRenderer: Frame skipped at 00:03:55.2000000
     Debug - VideoRenderer: Frame skipped at 00:03:59.1600000
     Debug - VideoRenderer: Frame skipped at 00:04:00.5600000
     Debug - VideoRenderer: Frame skipped at 00:04:02.2000000
     Debug - VideoRenderer: Frame skipped at 00:04:04.9600000
     Debug - VideoRenderer: Frame skipped at 00:04:07.2800000
     Debug - VideoRenderer: Frame skipped at 00:04:07.4400000
     Debug - VideoRenderer: Frame skipped at 00:04:07.7600000
     Debug - VideoRenderer: Frame skipped at 00:04:07.8000000
     Debug - VideoRenderer: Frame skipped at 00:04:09.9200000
     Debug - VideoRenderer: Frame skipped at 00:04:09.9600000
     Debug - VideoRenderer: Frame skipped at 00:04:11.0800000
     Debug - VideoRenderer: Frame skipped at 00:04:11.4400000
   Warning - SYNC AUDIO: LATENCY:      0.097 | SKIP (samples being rendered too late)
   Warning - SYNC AUDIO: LATENCY:      0.063 | SKIP (samples being rendered too late)
     Debug - VideoRenderer: Frame skipped at 00:04:13.0400000
     Debug - VideoRenderer: Frame skipped at 00:04:13.1200000
     Debug - VideoRenderer: Frame skipped at 00:04:13.1600000
     Debug - SYNC-BUFFER: Started.
     Debug - SYNC-BUFFER: Finished. Clock set to    253.640
   Warning - SYNC AUDIO: LATENCY:     -0.188 | WAIT (samples being rendered too early)
   Warning - SYNC AUDIO: LATENCY:     -0.078 | WAIT (samples being rendered too early)
     Debug - SYNC-BUFFER: Started.
     Debug - SYNC-BUFFER: Finished. Clock set to    254.560
   Warning - SYNC AUDIO: LATENCY:     -0.186 | WAIT (samples being rendered too early)
   Warning - SYNC AUDIO: LATENCY:     -0.085 | WAIT (samples being rendered too early)
     Debug - VideoRenderer: Frame skipped at 00:04:14.9600000
     Debug - VideoRenderer: Frame skipped at 00:04:15
     Debug - VideoRenderer: Frame skipped at 00:04:15.0400000
   Warning - SYNC AUDIO: LATENCY:      0.021 | SKIP (samples being rendered too late)
     Debug - VideoRenderer: Frame skipped at 00:04:15.0800000
     Debug - VideoRenderer: Frame skipped at 00:04:15.8400000
     Debug - VideoRenderer: Frame skipped at 00:04:17.6400000
     Debug - VideoRenderer: Frame skipped at 00:04:17.7600000
     Debug - VideoRenderer: Frame skipped at 00:04:19.1200000
     Debug - VideoRenderer: Frame skipped at 00:04:21.8000000
     Debug - VideoRenderer: Frame skipped at 00:04:22.9200000

**Comment by StevenGilligan** [comment] 2017-09-12 14:21
I did some digging to find out where the bug was introduced for windows 7 PCs, I went back to the previous build I had that worked with no issues since I had no updated my local branch in a long time and picked checkouts manually until I could pinpoint which one had the stuttering issues. 

For my windows 7 PC, stuttering starts with this commit : https://github.com/unosquare/ffmediaelement/commit/2bb920d848e2e7001b67223fe6ea00be0cd9bc27 

Every build I do based on commits before that have no playback issues on windows 7, and every commit after this one have some stuttering, some are worse than others. I didn't check this on my windows 10 pc also because it was pretty time consuming already on a single PC. Hope this helps!

**Comment by mariodivece** [comment] 2017-09-12 15:33
Wow! I think you just found exactly what the issue is. It seems to be pointing to the default time slice for timers and threads in windows 7. I will try to update the code today and will ask you to test again. This is extremely helpful!

**Comment by mariodivece** [comment] 2017-09-12 17:54
Ok, can you try again with my latest commit please? Let me know how testing goes.

**Comment by StevenGilligan** [comment] 2017-09-12 18:49
Everything's playing perfectly with your fix!

**Comment by mariodivece** [comment] 2017-09-12 20:22
@guoluming and @lyapple2008 could you guys check on your end?
@StevenGilligan All the kudos to you for identifying the exactly where the issue started appearing.

**Comment by guoluming** [comment] 2017-09-13 02:07
Everything's playing perfectly with your fix! Thanks a lot!

**Comment by mariodivece** [comment] 2017-09-13 02:18
Ok. Closing now then! Thanks you guys.

**Closed by mariodivece** 2017-09-13 02:18 UTC
Labels: bug
