### ISSUE TITLE
HLS: Retry Failed Connections

### ISSUE THREAD

**Issue by 9Arca9** [unosquare/ffmediaelement#156] opened 2018-02-04 09:25 UTC
Currently working with HLS, and the streaming server isn't know for stability. 

My current issue now is informing the player to attempt to reconnect on failed connections, currently working around this by waiting for the media state to end, then programmatically telling the player to play the same stream again.

Something along the lines of MediaElement.ReConnect(bool RetryOnFail, int RetryAttempts, int TimeBetweenAttemptsInMs)

If there's a way to do this outside of the api, without hacking it too much, lemme know.

Edit:
I have located the Options inputted into MediaInitializingRoutedEventArgs, which i think i manipulate for now, but exposing something like MediaElement.Options to add options to the player before playing the video would be beneficial. 

Edit 2:
Filing tickets at 5AM on little sleep is a bad idea kids. Solution to manipulating the Http headers/user agent and reconnect attempts is to add a new event to Media Initializing event handler to the player.  Here you can add options to the MediaInitializingRoutedEventArgs passed (e.Option.Input). Which should take effect before starting the stream. Going to test for effectiveness. 

Edit 3:
This issue seems to be at FFMPEGs level. Further looking into it, there doesn't seem to be any command line arguments to attempt to reconnect to a forbidden or 404 more than once. I will keep this up dated but it seems like this might have to be handled by reading when FFMPEG fails and try to reconnect using the same video buffer if it succeeds.

**Comment by mariodivece** [comment] 2018-02-04 23:52
Is there any way you can reproduce what you need to in ffplay.exe? If so, what are the command-line arguments?

**Comment by 9Arca9** [comment] 2018-02-05 00:24
Looking here for arguments : https://ffmpeg.org/ffmpeg-protocols.html#hls 

HLS, and Http, don't actually support what we need.

reconnect_streamed = Attempts to reconnect on a failure, but only once. If reconnect yields another fail, ffmpeg will stop trying to connect.
reconnect_delay_max = how long for http to wait for server response.

Doesn't seem like anything built into ffmpeg can be changed to natively support this. I am currently trying to attempt to force FFMPEG to reconnect each time it gives me back an error that contains 403. For x amount of reconnect attempts. I don't mind if it gives up, so long as I can somehow make the player understand that it needs to reconnect to stream even while playing content, and when reconnected feed the video into the same pipe.

**Comment by mariodivece** [comment] 2018-02-05 00:30
Maybe somehow monitor the `BufferingProgress` dependency property and the `BufferingStarted` and `BufferingEnded` routed events to come up with logic to close and re-open the stream to the last position it was able to retrieve. Sorry I can't be of more help. I am open to specific suggestions on how to solve the issue. I am closing this one for now until more information becomes available.

**Comment by 9Arca9** [comment] 2018-02-05 00:39
Here's what I am thinking:

- Monitoring FFME you can get when the internal media has been disconnected from the source.
- This means the HTTP stream is now closed.
- Using the disconnect as a trigger see what the player is doing. If the player is still playing, it means we got disconnected from the source while there was information in the buffer.
- Attempt to re-open the http stream url, so long as the video buffer has information. 
- Upon each connection attempt, check if the video has finished its buffer. If so, stop trying to reconnect. If not, keep trying to reconnect (Opening http for video stream information)
- If the stream was successfully reopened, and we are still playing video, add the incoming bytes to the existing buffer.


.... Does that help at all?

**Comment by mariodivece** [comment] 2018-02-05 00:49
Ok, let's go one by one:
You said: "Monitoring FFME you can get when the internal media has been disconnected from the source."
How exactly do I do this? I don't have a handle to internal FFmpeg socket. Even if I did, FFmpeg might want to handle multiple concurrent connections so a closed handle might not even mean the input has been closed.

**Comment by 9Arca9** [comment] 2018-02-05 00:57
Okay, try to bare with me as my technical knowledge is probably not up to par with yours.

In the FFME logging handler you have access to when the 403 (We'll just use my issue for now) happens. After the initial 403 ffmpeg will attempt to reconnect. The actual issue I am facing is that this reconnect attempt only happens once. If it fails again, ffmpeg completely gives up on the connection. The buffer runs dry, the download progress is stopped. So, is there a way for us to queue up ffmpeg and say "Connect to 403ed stream" when this happens? If the behavior I am seeing is accurate (and it might not be) ffmpeg should have that socket closed and disposed, because it's not longer receiving any information from the source.

**Comment by mariodivece** [comment] 2018-02-05 03:31
I am going to reopen this in case this is solvable. We obviously can't rely on logging messages. There has to be a field in AVInputFormat somewhere (maybe the pb struct?)
Documentation Reference: https://libav.org/documentation/doxygen/master/

**Comment by 9Arca9** [comment] 2018-02-05 05:36
Is it possible to tell when the decoder is no longer processing frames? Then if it's no longer processing avio_check (url, flags) to see that status of the stream we are using to see if it returns a 304 and keep loading the stream until it works? 

I am just throwing out ideas to see if anything works.

**Comment by tpazman** [comment] 2018-02-13 14:55
This can be solved extrenally by running an in-app proxy. I have the player in a wrapper that also starts up an HTTPListener. Then instead of giving the MediaElement http://server.com/file.m3u8, I rewrite this URL to http://localhost:58392/http/80/server.com/file.m3u8. FFmpeg hits the proxy with requests and the proxy parses the URL from the request, gets the file and returns it to ffmpeg. I do this for different reasons (HLS local caching/prefetching and the ability to rewrite .m3u8 files on the fly) but in your case your proxy could just retry however many times you want.

**Comment by mariodivece** [comment] 2018-02-13 16:41
@tpazman wow! that's an excellent idea! any code sample you could share here?

**Comment by mariodivece** [comment] 2018-02-17 23:49
I have decided to close this issue because it is outside of the scope of the MediaElement itself. If @tpazman provides some sample code I might be able to add this as a utility library on the side like I did with the m3u8 playlist loader/saver.

**Closed by mariodivece** 2018-02-17 23:49 UTC
Labels: question
