### ISSUE TITLE
Video Freeze when navigating between multiple MediaElement instances

### ISSUE THREAD

**Issue by LouisCPro** [unosquare/ffmediaelement#287] opened 2018-10-08 14:44 UTC
WPF App - MediaElement in multiple UserControl (Tab Control Children)

When passing from one Tab to another (each represent an rtsp stream from a camera, it finally freeze the stream on the several tabs, or even refuse to reconnect, or finally fail.

## Issue Categories

 - [X] Not sure

## Version Information

 - [X] NuGet Package v4.0.270

## Steps to Reproduce

 1. Create an App with a TabControl containing several TabItem with a MediaElement
 2. Click on Play on each Tab Item
 3. GetBack on previous items
 4. Stream finished in a freezed image, and the camera refuse to open a new stream after a while (as if the stream was kept open even if I do a Stop/Close on UserControl Visibility ChangedEvent

## Expected Results

 - As WPF has a bad way of playing with UserControl when the Visibility changes (deals as an unload / Load), I would like to be sure that the MediaElement refer to the same behavior or not ?

**Comment by mariodivece** [comment] 2019-03-18 02:35
How many tabs did you add? What is the resolution of these videos? What is the CPU usage when all the videos are running?

**Comment by LouisCPro** [comment] 2019-03-19 09:36
@mariodivece,

Even with few tabs (3 or 4). The resolution of each cam is about FULLHD. The CPU usage is OK, with about 50/60%, knowing that probably H264 stream decoding is done by the NVIDIA Graphic Card GPU.

I think the problem is not related to resources bur more on control disposing during Tab changed event.

**Comment by mariodivece** [comment] 2019-03-19 12:52
The problem is that this is expected WPF behavior. 
https://www.google.com/search?q=wpf+prevent+dispose+when+tab+changes
Loos like the tab control removes times from the vial tree when it changes. Your best bet would be to create a new user control that places medicamentos un layers that you move up and down to make them visible. Just an idea obviously...

**Comment by mariodivece** [comment] 2019-03-19 12:54
Another item that might be helpful
https://www.codeproject.com/Articles/212233/Persist-the-Visual-Tree-when-switching-tabs-in-the

**Comment by LouisCPro** [comment] 2019-03-19 13:29
Yes, that's it !

But however the control is disposed, it should not freeze !

The implementation of an IDisposable interface should be nice, and would help by calling Control.Dispose() to correctly manage the MediaElement destruction.

Dont you think ?

**Comment by mariodivece** [comment] 2019-03-19 16:33
You are correct. Calling dispose should not freeze the video. I will repro the issue and try to fix it.

**Comment by LouisCPro** [comment] 2019-03-19 17:43
OK,

Thanks !

**Comment by mariodivece** [comment] 2019-03-19 23:18
You will need to attach a zip file with a sample project. I created a 4-tabs project with webcam RTSP streams and I can switch streams without any issues and no video freeze. I am using ffme 2.80 (not 2.70 as your bug report) and .NET Framework 4.7.2

My cams are also Full HD and my CPU usage is much lower ~12%. I am not using any hardware decoding either.

**Comment by mariodivece** [comment] 2019-03-22 02:09
could you send me the zip file that reproduces your issue with NuGet 2.80 please?

**Comment by LouisCPro** [comment] 2019-03-22 16:13
Hi Mario,

I'm not on dev stuff at the moment. I'll be back on that subject around this summer.
Nevermind, there's no stress on that part for me as this functionnality is for future use.

Thanks for your time,

Louis

**Comment by mariodivece** [comment] 2019-03-31 17:48
The next version implements standard WPF control behavior. When removed from the visual tree, the media will automatically close. Please feel free to open a new issue if further feedback needs to be provided. Closing this one for now.

**Closed by mariodivece** 2019-03-31 17:48 UTC

**Comment by LouisCPro** [comment] 2019-04-01 12:49
Hi Mario,

Thanks for the effort. I'll try that soon !

Regards,

**Comment by LouisCPro** [comment] 2019-09-18 09:31
Hi Mario,

Tests Done ! I also did something around my WPF TabControl, to avoid Load/Unload on TabChanged, and it is much better now !
