### ISSUE TITLE
Running instances concurrently: ArgumentException

### ISSUE THREAD

**Issue by faddox** [unosquare/ffmediaelement#133] opened 2018-01-10 17:20 UTC
Is this a thread issue?  how can I resolve this issue?

**Here is the exception detail:**
System.ArgumentException was unhandled
  HResult=-2147024809
  Message=An item with the same key has already been added.
  Source=mscorlib
  StackTrace:
       at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
       at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
       at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
       at FFmpeg.AutoGen.ffmpeg.<>c__DisplayClass7_0.<.cctor>b__0(String name, Int32 version)
       at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__7_1497(SwsContext* context, Int32 srcW, Int32 srcH, AVPixelFormat srcFormat, Int32 dstW, Int32 dstH, AVPixelFormat dstFormat, Int32 flags, SwsFilter* srcFilter, SwsFilter* dstFilter, Double* param)
       at FFmpeg.AutoGen.ffmpeg.sws_getCachedContext(SwsContext* context, Int32 srcW, Int32 srcH, AVPixelFormat srcFormat, Int32 dstW, Int32 dstH, AVPixelFormat dstFormat, Int32 flags, SwsFilter* srcFilter, SwsFilter* dstFilter, Double* param)
       at Unosquare.FFME.Decoding.VideoComponent.MaterializeFrame(MediaFrame input, MediaBlock& output, List`1 siblings)
       at Unosquare.FFME.Decoding.MediaContainer.Convert(MediaFrame input, MediaBlock& output, List`1 siblings, Boolean releaseInput)
       at Unosquare.FFME.Decoding.MediaBlockBuffer.Add(MediaFrame source, MediaContainer container)
       at Unosquare.FFME.MediaElementCore.AddBlocks(MediaType t)
       at Unosquare.FFME.MediaElementCore.RunFrameDecodingWorker()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by mariodivece** [comment] 2018-01-10 17:59
NuGet Package? Master Branch? Any sample file you could provide please? Does it happen with all media files you have tested? When does this occur? I need more info.

**Comment by mariodivece** [comment] 2018-01-10 18:13
On the Windows Sample, I added the following to the XAML and it works as expected...
```xml
        <ffme:MediaElement Name="Media" Background="Black" Grid.Row="0" Grid.Column="0"></ffme:MediaElement>
        <ffme:MediaElement Source="{Binding ElementName=Media, Path=Source}" Name="PIP" Background="Black" Grid.Row="0" Grid.Column="0" Width="300" Height="250" HorizontalAlignment="Left" VerticalAlignment="Top"></ffme:MediaElement>
```

Two instances running just fine...
![image](https://user-images.githubusercontent.com/351978/34788252-98bcda82-f5ff-11e7-9b3c-0e0367cad5fc.png)

**Comment by faddox** [comment] 2018-01-10 18:13
Latest NuGet package FFME.Windows -Version 3.4.0.2-b7. 
Used ffmpg-3.4-win32-shared.zip.
I can't directly compile the source code since I don't have visual studio 2017.
I have a wpf application, two windows, each host a ffmpeg media element, application starts, two windows created, each opens its own video file, both of them had MediaOpened event fired, then before any of the windows show up, I got this exception.  It seems not video file related.
But this is not happening every time I run my program, sometimes starts fine without issue, but it still happens quite often.

**Comment by mariodivece** [comment] 2018-01-10 18:22
Any way you can provide the source or a sample app? I need to be able to repro the issue and it seems like an easy fix: locking some dictionary.

**Comment by mariodivece** [comment] 2018-01-10 18:34
It looks like The following static initializer might be causing the issue.
https://github.com/Ruslan-B/FFmpeg.AutoGen/blob/719a4ea0650be2e510ab576d8395cb065c074511/FFmpeg.AutoGen/FFmpeg.cs#L28

I still need to be able to reproduce...

**Comment by mariodivece** [comment] 2018-01-10 18:36
Are you by any chance calling: ```ffmpeg.GetOrLoadLibrary``` somewhere in your code?

**Comment by faddox** [comment] 2018-01-10 19:13
No.  I have not directly called any ffmpeg function in my code. 
I will get sample app for you shortly.

**Comment by faddox** [comment] 2018-01-10 19:47
[VideoTraining.zip](https://github.com/unosquare/ffmediaelement/files/1620217/VideoTraining.zip)
I have to remove all the files in ffmpeg folder in order to make the file size small.
Thanks for helping!

**Comment by mariodivece** [comment] 2018-01-11 15:43
Your sample program acts very strangely. On VS 2015 it gives me an Out of Memory Exception. On VS 2017, media stutters and and does not play smoothly. I believe it is because of the way you might be initializing your main windows. I don't know and I don't have too much time to troubleshoot your particular issue. I have written a very simple sample using the beta 7 NuGet package it works very smoothly. It should support quite a few videos running concurrently. Please comment on this issue if you are able to troubleshoot the issue in your app. Here's the sample.

[Unosquare.FFME.TwoWindows.zip](https://github.com/unosquare/ffmediaelement/files/1623128/Unosquare.FFME.TwoWindows.zip)

**Comment by faddox** [comment] 2018-01-11 15:49
I can't download the sample above, it gives me 404 page.

**Comment by mariodivece** [comment] 2018-01-11 15:50
I'm uploading again. I was uploading when GitHub was having issues.
[Unosquare.FFME.TwoWindows.zip](https://github.com/unosquare/ffmediaelement/files/1623189/Unosquare.FFME.TwoWindows.zip)

**Comment by faddox** [comment] 2018-01-11 16:15
I run your sample code on my machine.  I have to change project's target network to 4.6.1 because it is one installed on my machine and it will allow me to run "Install-Package FFME.Windows -Version 3.4.0.2-b6", after I make the video path update in your sample program, and compiled, when I run your sample program, upon start up, it throw the same exception as I have before.  It makes me think whether this is .net framework related issue.

**Comment by mariodivece** [comment] 2018-01-11 16:48
What version of Windows are you running? Could you try on a different machine? What happens if you run the application WITHOUT the debugger attached?

**Comment by faddox** [comment] 2018-01-11 16:52
I am running Windows 10 Enterprise.
I have tried with Release version, it had the same issue, sometimes it will throw exception upon start up.

**Comment by faddox** [comment] 2018-01-11 17:30
What's the version of netstandard.dll are you using, I have to add it to the project reference.
Do you not need it for this project?

**Comment by mariodivece** [comment] 2018-01-11 17:43
It's in the README
![image](https://user-images.githubusercontent.com/351978/34838671-9b50056a-f6c4-11e7-9f25-c58f06d5fe28.png)

**Comment by tenisak** [comment] 2018-01-11 17:45
If this helps you - I tried to test _Unosquare.FFME.TwoWindows.zip_ with the latest NuGet package (b7) on Windows 10. I ran the app repeatedly (about 10x) and did not make any error. Everything works well.

**Comment by mariodivece** [comment] 2018-01-11 17:52
@tenisak yep... I think it is definitely an isolated case with @faddox 's setup

**Comment by faddox** [comment] 2018-01-11 18:00
I have installed Microsoft .Net Core SDK v2.1.3 (x64) on my machine from beginning.
@mariodivece Do you mean setup of my computer? or VS2015.
I can't run Unosquare.FFME.TwoWindows.zip 10 times without problem.

**Comment by tenisak** [comment] 2018-01-14 07:01
@faddox Please try to compile your code in VS 2017. (Free and/or trial versions [here on visualstudio.com](https://www.visualstudio.com/))

**Comment by faddox** [comment] 2018-01-16 18:16
I have downloaded and installed visual studio 2017 community version, recompiled Unosquare.FFME.TwoWindows.zip project, I still have issue during start up, here is the debug information from Output window:

Info - INIT FFMPEG: 3.4
Info - INIT FFMPEG: 3.4
Debug - OpenCommand: Entered
Debug - OpenCommand: Entered
Debug - COMP AUDIO: Start Offset:      0.000; Duration:    304.019
Debug - COMP AUDIO: Start Offset:      0.000; Duration:    269.723
Debug - COMP VIDEO: Start Offset:      0.000; Duration:    303.970
Debug - COMP VIDEO: Start Offset:      0.000; Duration:    269.703
Debug - OpenCommand: Completed
Debug - OpenCommand: Completed
Debug - Command Queue (1 commands): Before ProcessNext
Debug - Command Queue (1 commands): Before ProcessNext
Debug -    Play - ID: 200 Canceled: False; Completed: False; Status: Created; State: 
Debug -    Play - ID: 201 Canceled: False; Completed: False; Status: Created; State: 
Debug - SYNC-BUFFER: Started.
Debug - SYNC-BUFFER: Started.
An unhandled exception of type 'System.ArgumentException' occurred in ffme.common.dll
An item with the same key has already been added.

**Comment by mariodivece** [comment] 2018-01-16 22:05
strange. What happens when you use my sample: https://github.com/unosquare/ffmediaelement/files/1623189/Unosquare.FFME.TwoWindows.zip
Is that causing an issue as well?

**Comment by mariodivece** [comment] 2018-01-17 21:43
Did you try with my sample and latest commit?

**Comment by faddox** [comment] 2018-01-17 21:49
I have not tried your sample code with latest commit on unosquare/ffmediaelement.
I will try to get to it tomorrow.

**Comment by mariodivece** [comment] 2018-01-18 17:07
Any updates here?

**Comment by faddox** [comment] 2018-01-18 18:06
I have compiled the ffmpegmedia source in visual studio 2017, and used its generated ffme.common.dll and ffme.win.dll in my project, I don't see any ArgumentException during start up anymore.

**Comment by mariodivece** [comment] 2018-01-18 19:02
Ok, I'll close the issue now. If you'd like to use the latest NuGet (beta 9), that is fine. It has all the commits to date.

**Closed by mariodivece** 2018-01-18 19:02 UTC
Labels: question

**Comment by faddox** [comment] 2018-01-18 20:59
Many thanks!!!
