### ISSUE TITLE
Media URL Encoding - Change Filename Encoding

### ISSUE THREAD

**Issue by mariodivece** [unosquare/ffmediaelement#308] opened 2018-12-13 12:59 UTC
Adding this line in the user code before calling MediaElement.Open does not work:
```cs
string path = Encoding.GetEncoding(1252).GetString(Encoding.UTF8.GetBytes(@"C:\Downloads\mp3\力 ちから.mp3"));
await mediaElement.Open(new Uri(path));
// openUrl in MediaContainer.StreamInitialize() == åŠ› ã%C2%81¡ã%C2%81‹ã‚‰.mp3
// Error -2: No such file or directory
```

But adding this line directly in the MediaContainer.StreamInitialize() method works:
```cs
string openUrl = Encoding.GetEncoding(1252).GetString(Encoding.UTF8.GetBytes($"{prefix}{MediaUrl}"));
// openUrl = åŠ› ã¡ã‹ã‚‰.mp3
// No error
```

@mariodivece, what do you think about that?

Thanks.

_Originally posted by @CyberSinh in https://github.com/unosquare/ffmediaelement/issues/235#issuecomment-446726030_

**Comment by mariodivece** [comment] 2018-12-13 13:02
Thanks @CyberSinh -- Could you also try instead of 1252 fixed encoding, getting the Default ecoding as: `Encoding.GetEncoding(0)` please and let me know the results?

**Comment by AntonyCorbett** [comment] 2018-12-13 14:41
For reference, here is the ffmpeg bug report (7 years old):

https://trac.ffmpeg.org/ticket/819

A possible solution is to open the url ourself and supply avformat_open_input() with a buffer rather than the url string: https://mw.gl/posts/ffmpeg_custom_io/

**Comment by CyberSinh** [comment] 2019-01-04 10:22
Hi @mariodivece,
The development of ffmediaelement seems to have stopped a few months ago. When do you think you will be able to resume maintenance work?
Thanks.

**Comment by mariodivece** [comment] 2019-01-04 15:22
I am super busy at the moment. I estimate I will be back on this hobby project by mid March. In the meantime PRs are welcome

**Comment by CyberSinh** [comment] 2019-03-25 15:36
Hi Mario. Could it be possible to fix this issue for the next release (2.90) instead of 3.0? Because the bug is quite annoying for users. Thanks.

**Comment by mariodivece** [comment] 2019-03-25 15:40
Sure, but I am still not sure what is the proposed solution. The underlying seems liek an iunderlying ffmpeg problem. Also, remember you can use the IMediaInputStream to implement a custom input as I so in the sample with FileInputStream. check it, Otherwise, let me know what the proposed solution is.

**Comment by CyberSinh** [comment] 2019-03-25 16:39
I'm not sure too what is the best solution to workaround with the issue (playing with `Encoding` or implementing `IMediaInputStream`) but I think `ffmediaelement` should provide a built-in solution for opening all unicode file path by default ("it just works"). Like `ffplay.exe` which is able to manage with unicode file path and deal with this common and known technical `ffmpeg` issue.

**Comment by mariodivece** [comment] 2019-03-30 19:54
could you provide a couple of examples of how it does not open and what are you using as a workaround? What are the full `Source` urls that are not working? I am having trouble reproducing the issue.

**Comment by CyberSinh** [comment] 2019-03-30 21:37
Hi Mario, the step to reproduce the issue is specified in the #235 thread. Do not hesitate if you any other info.

**Comment by mariodivece** [comment] 2019-05-04 22:00
I think this was finally fixed on the dependent library FFmpeg.Autogen.
Check out: https://github.com/Ruslan-B/FFmpeg.AutoGen/issues/96
It looks like it was a common issue unrelated directly to FFME. Could you test it out with my latest commit and let me know if I can finally close this one?

**Comment by CyberSinh** [comment] 2019-05-05 10:09
Hi Mario. I tested with the your latest commit and the issue seems finally fixed! Thanks! You can close the issue.

**Closed** 2019-05-05 11:48 UTC
Labels: bug, enhancement
