### ISSUE TITLE
When using the Open method with Source set to null in ffme: Media Element the video will not render at all

### ISSUE THREAD

**Issue by gquinn1998** [unosquare/ffmediaelement#417] opened 2019-07-03 13:14 UTC
When using the Open method with Source set to null in ffme: Media Element the video will not render at all

I am using the following versions:
FFME.Windows    v4.1.310   using .Net Framework 4.6.1
FFmpeg.AutoGen v4.1.0.5 using .Net Framework 4.6.1

I am using WPF with C#.
When I supply a URI to the Source the Video is played but when I supply the URI to the open method it does not play. I plan to use this by streaming data to the ffme: Media Element through the interface IMediaInputStream, I have already done this and I get the same outcome as the URI in the Open method.

I have looked through the Sample code and I have everything in it and the Open method just does not work.

Is there any other configuration that I may have to do that I am unaware of?

**Comment by mariodivece** [comment] 2019-07-03 13:18
The sample app is build using the Open method. Have you checked out the code in the sample app?
```csharp
                    var uriString = a as string;
                    if (string.IsNullOrWhiteSpace(uriString))
                        return;

                    var m = App.ViewModel.MediaElement;

                    // m.Source = new Uri(uriString); // you can also set the source to the Uri to open
                    var target = new Uri(uriString);
                    if (target.ToString().StartsWith(FileInputStream.Scheme, StringComparison.OrdinalIgnoreCase))
                        await m.Open(new FileInputStream(target.LocalPath));
                    else
                        await m.Open(target);
```

Would it be possible to provide me with a very simple project that reproduces the issue you are describing? (Open method not working)

**Comment by gquinn1998** [comment] 2019-07-03 14:13
Hi Mario,

Yes, I looked at all the example and I tried it out and it does not work.
Here is the sample code from a very simple project to just play the video through a stream:

using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using System.Windows.Controls;
using System.Windows.Threading;
using FFmpeg.AutoGen;
using Unosquare.FFME;
using Unosquare.FFME.Common;

namespace WpfApplication6.Views
{
    /// <summary>
    /// Interaction logic for MainView.xaml
    /// </summary>
    public partial class MainView : UserControl
    {
        public MainView()
        {
            InitializeComponent();

            Video.MessageLogged += VideoOnMessageLogged;
            Video.MediaReady += VideoOnMediaReady;
            Video.MediaFailed += VideoOnMediaFailed;
            Video.MediaInitializing += VideoOnMediaInitializing;
            Video.MediaOpening += VideoOnMediaOpening;
            Video.MediaOpened += VideoOnMediaOpened;
            Video.MediaClosed += VideoOnMediaClosed;
            Video.MediaChanged += VideoOnMediaChanged;
            Video.MediaStateChanged += VideoOnMediaStateChanged;
            Video.RenderingVideo += VideoOnRenderingVideo;
            Video.BufferingStarted += VideoOnBufferingStarted;

            Video.RendererOptions.UseLegacyAudioOut = true;
            Video.RendererOptions.VideoRefreshRateLimit = 25;
            
            GetVideo();
        }

        private void VideoOnBufferingStarted(object sender, EventArgs e)
        {
            var message = e;
        }

        private void VideoOnRenderingVideo(object sender, RenderingVideoEventArgs e)
        {
            var message = e;
        }

        private async Task GetVideo()
        {
            var asm = Assembly.GetExecutingAssembly();
            var path = Path.GetDirectoryName(asm.Location);
            if (path != null)
            {
                path = Path.Combine(path, @"Resources\grindingcoffee_h264.mp4");
                //Video.Source = new Uri(path, UriKind.Absolute);
                await Video.Open(new FileInputStream(path));
                //await Video.Open(new Uri(path, UriKind.Absolute));
                //Video.Source = new Uri(path, UriKind.Absolute);
                //Video.Position = TimeSpan.FromSeconds(2);
            }
        }

        private void VideoOnMediaStateChanged(object sender, MediaStateChangedEventArgs e)
        {
            switch (e.MediaState)
            {
                case MediaPlaybackState.Manual:
                    break;
                case MediaPlaybackState.Play:
                    var video = sender as Unosquare.FFME.MediaElement;
                    //this.Dispatcher?.Invoke(() => { video.Play(); });
                    break;
                case MediaPlaybackState.Close:
                    var message1 = "Closing";
                    break;
                case MediaPlaybackState.Pause:
                    break;
                case MediaPlaybackState.Stop:
                    break;
                default:
                    throw new ArgumentOutOfRangeException();
            }
        }


        private void VideoOnMediaChanged(object sender, MediaOpenedEventArgs e)
        {
            
        }

        private void VideoOnMediaClosed(object sender, EventArgs e)
        {
            var video = sender as Unosquare.FFME.MediaElement;
        }

        private void VideoOnMessageLogged(object sender, MediaLogMessageEventArgs e)
        {
            Console.WriteLine(e);
        }

        private void VideoOnMediaReady(object sender, EventArgs e)
        {
            var video = sender as Unosquare.FFME.MediaElement;
            video?.Play();
        }

        private void VideoOnMediaOpened(object sender, MediaOpenedEventArgs e)
        {
            var info = e.Info;
            
        }

        private void VideoOnMediaFailed(object sender, MediaFailedEventArgs e)
        {
            var info = e.ErrorException;
            
        }

        private void VideoOnMediaOpening(object sender, MediaOpeningEventArgs e)
        {
            var options = e.Options;
            var videoElement = sender as Unosquare.FFME.MediaElement;

            e.Options.SubtitlesDelay = TimeSpan.Zero;
            e.Options.IsTimeSyncDisabled = false;
            e.Options.MinimumPlaybackBufferPercent = 1;

            var audioStreams = e.Info.Streams.Where(kvp => kvp.Value.CodecType == AVMediaType.AVMEDIA_TYPE_AUDIO).Select(kvp => kvp.Value);
            var englishAudioStream = audioStreams
                .FirstOrDefault(s => s.Language != null && s.Language.StartsWith("en", StringComparison.OrdinalIgnoreCase));

            if (englishAudioStream != null)
                e.Options.AudioStream = englishAudioStream;

            var url = new Uri(e.Info.MediaSource);
            var mediaFilePath = url.IsFile || url.IsUnc ? Path.GetFullPath(url.LocalPath) : string.Empty;
            var seekIndex = Library.CreateVideoSeekIndex(mediaFilePath, e.Options.VideoStream.StreamIndex);
            e.Options.VideoSeekIndex = seekIndex;

            var deviceCandidates = new[]
            {
                AVHWDeviceType.AV_HWDEVICE_TYPE_CUDA,
                AVHWDeviceType.AV_HWDEVICE_TYPE_D3D11VA,
                AVHWDeviceType.AV_HWDEVICE_TYPE_DXVA2
            };

            // Hardware device selection
            if (e.Options.VideoStream.FPS <= 30)
            {
                foreach (var deviceType in deviceCandidates)
                {
                    var accelerator = e.Options.VideoStream.HardwareDevices.FirstOrDefault(d => d.DeviceType == deviceType);
                    if (accelerator == null) continue;
                    e.Options.VideoHardwareDevice = accelerator;
                    break;
                }
            }

            var height = e.Options.VideoStream.PixelHeight;
            var width = e.Options.VideoStream.PixelWidth;
            e.Options.VideoForcedFps = 25;

            this.Dispatcher?.Invoke(() =>
            {
                videoElement.RendererOptions.AudioDisableSync = false;
                videoElement.RendererOptions.UseLegacyAudioOut = true;
                videoElement.RendererOptions.VideoRefreshRateLimit = 0;

                videoElement.Width = width;
                videoElement.Height = height;
            }, DispatcherPriority.Render);
        }

        private void VideoOnMediaInitializing(object sender, MediaInitializingEventArgs e)
        {
            if (e.MediaSource.StartsWith("http://", StringComparison.OrdinalIgnoreCase) ||
                e.MediaSource.StartsWith("https://", StringComparison.OrdinalIgnoreCase))
            {
                e.Configuration.PrivateOptions["user_agent"] = $"{typeof(ContainerConfiguration).Namespace}/{typeof(ContainerConfiguration).Assembly.GetName().Version}";
                e.Configuration.PrivateOptions["headers"] = "Referer:https://www.unosquare.com";
            }

            e.Configuration.GlobalOptions.FlagNoBuffer = false;
            e.Configuration.GlobalOptions.ProbeSize = 8192;
            e.Configuration.GlobalOptions.MaxAnalyzeDuration = System.TimeSpan.FromSeconds(1);
            e.Configuration.GlobalOptions.PacketSize = 4096;
        }
    }
}

**Comment by mariodivece** [comment] 2019-07-03 15:05
Lets' start with the sample app. When you click the + sign on the playlist panel and add
`customfile:///C:/ffme-testsuite/video-subtitles-03.mkv` (obviously adjusting the path to a real video file) what happens? 

Are you sure the file you are pointing to is not an Embedded Resource?
Have you verified the fill path to the file exists?
What do you see in the output window?

If you want me to test with your code, you will need to provide a zip file with the project.

**Comment by gquinn1998** [comment] 2019-07-03 15:28
Hi Mario,

The file exists because I can see it's path and ffme:Media Element reads it in and I can see all the meta data on the file and the two streams namely Audio and Video.

The StreamUri is: 'file:///D:/VideoExample/WpfApplication6/bin/Debug/Resources/grindingcoffee_h264.mp4'

Here are the logs from the ffme:Media Element:
[21:11.345 | WRN | Engine.Commands     ] Direct Command 'Close' not accepted. Open media before closing or changing media.
[21:11.345 | WRN | Engine.Commands     ] Direct Command 'Close' not accepted. Open media before closing or changing media.
[21:11.345 | DBG | Engine.Commands     ] Direct Command 'Open' accepted. Perparing execution.
[21:11.361 | DBG | Engine.Commands     ] Direct Command 'Open' entered
[21:11.673 | INF | Engine.Commands     ] FFInterop.Initialize: FFmpeg v4.1.3
The thread 0x32e0 has exited with code 0 (0x0).
The thread 0x32e4 has exited with code 0 (0x0).
The thread 0x32e8 has exited with code 0 (0x0).
The thread 0x32ec has exited with code 0 (0x0).
The thread 0x32f0 has exited with code 0 (0x0).
The thread 0x32f4 has exited with code 0 (0x0).
The thread 0x32f8 has exited with code 0 (0x0).
The thread 0x32fc has exited with code 0 (0x0).
The thread 0x3300 has exited with code 0 (0x0).
The thread 0x3304 has exited with code 0 (0x0).
The thread 0x3308 has exited with code 0 (0x0).
The thread 0x330c has exited with code 0 (0x0).
The thread 0x3310 has exited with code 0 (0x0).
'WpfApplication6.exe' (CLR v4.0.30319: WpfApplication6.exe): Loaded 'C:\Users\GLENQU~1\AppData\Local\Temp\VisualStudio.XamlDiagnostics.12456\Microsoft.VisualStudio.DesignTools.WpfTap.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfApplication6.exe' (CLR v4.0.30319: WpfApplication6.exe): Loaded 'C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfApplication6.exe' (CLR v4.0.30319: WpfApplication6.exe): Loaded 'C:\windows\Microsoft.Net\assembly\GAC_MSIL\SMDiagnostics\v4.0_4.0.0.0__b77a5c561934e089\SMDiagnostics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfApplication6.exe' (CLR v4.0.30319: WpfApplication6.exe): Loaded 'C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Internals\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Internals.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfApplication6.exe' (CLR v4.0.30319: WpfApplication6.exe): Loaded 'C:\windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WpfApplication6.exe' (CLR v4.0.30319: WpfApplication6.exe): Loaded 'C:\windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[21:12.091 | DBG | Container.Component ] AUDIO - Start Time:      0.000; Duration:     12.245
[21:12.189 | DBG | Container.Component ] VIDEO - Start Time:      0.000; Duration:     12.240
[21:12.189 | INF | Container           ] Timing Offsets - Main Component: Video; Start Time:      0.000; Duration:     12.240; 
[21:12.429 | TRC | Element.Events      ] EVENT START: MediaStateChanged
[21:12.442 | DBG | Engine.Commands     ] Direct Command 'Open' completed. Result: True
'WpfApplication6.exe' (CLR v4.0.30319: WpfApplication6.exe): Loaded 'C:\windows\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll'. Cannot find or open the PDB file.
[21:12.745 | TRC | Element.Events      ] EVENT DONE : MediaStateChanged
[21:12.760 | TRC | Element.Events      ] EVENT START: MediaOpened
[21:12.765 | TRC | Element.Events      ] EVENT DONE : MediaOpened
[21:12.765 | TRC | Element.Events      ] EVENT START: MediaReady
[21:12.775 | TRC | Element.Events      ] EVENT DONE : MediaReady
The thread 0x3398 has exited with code 0 (0x0).
The thread 0x339c has exited with code 0 (0x0).
The thread 0x33a8 has exited with code 0 (0x0).
The thread 0x3390 has exited with code 0 (0x0).
[21:12.942 | TRC | Element.Events      ] EVENT START: MediaStateChanged
[21:12.943 | TRC | Element.Events      ] EVENT DONE : MediaStateChanged
[21:12.983 | TRC | Element.Events      ] EVENT START: MediaStateChanged
[21:12.983 | TRC | Element.Events      ] EVENT DONE : MediaStateChanged
[21:12.985 | TRC | Element.Events      ] EVENT START: MediaClosed
[21:12.985 | TRC | Element.Events      ] EVENT DONE : MediaClosed
The thread 0x33c0 has exited with code 0 (0x0).

I can also see that the Play state is being entered and then it immediately goes to the Media Close state.

**Comment by mariodivece** [comment] 2019-07-03 15:48
what is the effect of this in the ample app? -- Use the cutomfile:// URI scheme. The problem is that I just tested and it works just fine so I can't reproduce your issue.

**Comment by gquinn1998** [comment] 2019-07-03 16:22
[VideoExample.zip](https://github.com/unosquare/ffmediaelement/files/3355872/VideoExample.zip)

Hi Mario,

I have attached my sample file in a zip file. Just add in a video file at the path string. I added in the custom file but it still does not work.

**Comment by gquinn1998** [comment] 2019-07-04 13:57
Hi Mario,
Also on top of my current problem I am not able to load the sample project. It says imports are missing from the project file.
I am using Visual Studio 2017 Version 15.9.13

Here is a screen shot of my solution explorer:
![Solution Explorer](https://user-images.githubusercontent.com/25591117/60671857-f922af80-9e6b-11e9-9144-9739d1495c24.JPG)

**Comment by mariodivece** [comment] 2019-07-04 14:52
You will need to download vs 2019 preview and install for net core 3 preview 6

**Comment by gquinn1998** [comment] 2019-07-04 15:05
Can project files not be created for Visual Studio 2017? because I don't download previews from Microsoft any more because I have had to many problems in the past with previews, I always wait for the release version now before using it.

**Comment by RyanYANG52** [comment] 2019-07-05 04:50
Same problem here. If Call Close() before Open(), video will not show, it happens every other Open() call.
Test project : https://github.com/RyanYANG52/VideoPlayerTest
![test](https://user-images.githubusercontent.com/5292688/60698723-57f73000-9f23-11e9-9572-e453b7a493f0.gif)

**Comment by gquinn1998** [comment] 2019-07-05 09:08
When I looked at the Source Code the Open method actually calls the Close method internally maybe this is the problem!

Mario were you able to replicate the problem as well?

**Comment by mariodivece** [comment] 2019-07-06 20:55
I reviewed your code and your issue is that you ar both, Binding the `Source` dependency property and calling the `Open` method. Remove the `Source` binding
It should look something like
```csharp
<ffme:MediaElement Name="Video" Background="Black" LoadedBehavior="Play" />
```

Additionally, keep in mind that there is no way to pass a custom input stream as a `Source` binding (for obvious reasons)

**Comment by mariodivece** [comment] 2019-08-09 14:31
No further feedback was provided. Closing issue.

**Closed by mariodivece** 2019-08-09 14:31 UTC
Labels: invalid, question
