### ISSUE TITLE
Loading Video at Position gives inconsistent results 

### ISSUE THREAD

**Issue by woolersj** [unosquare/ffmediaelement#277] opened 2018-09-12 13:29 UTC
# Loading Video at a start position gives inconsistent results 

I have a WPF application that displays a list of videos and thumbnail for each. Selecting a video opens the file in the Media Player paused at a specific position of interest. (The frame from the thumbnail) 
When I switch between multiple videos the player doesn't always load at the same frame for a specific video even though the reported media position is always the same.
If I step forward then step back it seems to sort itself out and display the correct frame. 
It is usually only a few frames out (I have seen it as many as 6)
I am loading mpeg4 and h264 videos both 25fps.

My application used to work reliably in **NuGet Package 4.0.260.0** 
it doesn't however work since I updated to (https://github.com/unosquare/ffmediaelement/commit/445d258af9b25ba9be10ede8da1adfc3faf38c4d)

The reason I needed to update is because I also experienced of #243, which does seem to have been fixed in the latest code.

`Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at Unosquare.FFME.Platform.WindowsNativeMethods+NativeMethods.CopyMemory(IntPtr, IntPtr, UInt32)
   at Unosquare.FFME.Platform.WindowsNativeMethods.CopyMemoryParallel(IntPtr, IntPtr, UInt32)
   at Unosquare.FFME.Platform.WindowsNativeMethods.CopyMemory(IntPtr, IntPtr, UInt32)
   at Unosquare.FFME.Rendering.VideoRenderer.LoadTargetBitmapBuffer(Unosquare.FFME.Events.BitmapDataBuffer, Unosquare.FFME.Shared.VideoBlock)
   at Unosquare.FFME.Rendering.VideoRenderer+<>c__DisplayClass24_0.<Render>b__1()`

## Issue Categories

 - [*] Bug

## Version Information

The reported bug is not a problem in **NuGet Package 4.0.260.0**
but is in commit (https://github.com/unosquare/ffmediaelement/commit/445d258af9b25ba9be10ede8da1adfc3faf38c4d)

## Sample Code
I am using videos with a timecode overlayed on them so I can easily see if the same frame is always returned.

### XAML
```xml
<ffme:MediaElement Name="Media" Background="Black" LoadedBehavior="Manual" />
```

### Open a new Video
```csharp

// Open a new Video on selection changed
await Media.Open(new Uri(fileInfo.FullName));

// Seek to saved position
Media.Position = triggerTime;
```

I have also tried setting the position in the OnMediaOpened EventHandler 

### Set Position on Media Open
```csharp
Media.MediaOpened += OnMediaOpened;

private void OnMediaOpened(object sender, MediaOpenedRoutedEventArgs e)
{
    // Set a start position (see issue #66)
    Media.Position = triggerTime;
}
```

**Comment by woolersj** [comment] 2018-09-14 09:10
**Additional Info** 
I think there is a scenario where the media is not always properly initialised. 

When in this state 
- updating the position via the slider doesn't always update the displayed frame. 
- updating the position with Media.PositionPrevious  or Media.PositionNext takes you back to the start of the file. 

I have updated the Simple Test app from #66 which switches between two videos. 
This demonstrates the initial load position not being consistent 
[#277.zip](https://github.com/unosquare/ffmediaelement/files/2382690/277.zip)

**Comment by mariodivece** [comment] 2018-09-15 01:28
ok... I see the problem! Thank you for catching the issue and reporting. I'll fix this soon as it is an important feature.

**Comment by woolersj** [comment] 2018-09-15 06:51
Great Thank you! Could you provide any additional information as to what
you think is causing the problem. Or is there a workaround I can try?

**Comment by mariodivece** [comment] 2018-09-15 12:55
I believe positioncurrent positionprevious and positionnext are being set to incorrect values because of dependency property notifications. I need to update these properties on the wpf side of things the same or similar way I do with remainingduration. The position property is tricky to work with as a dependency property and this is a side effect. It can be fixed fairly easily though. I am currently refactoring the logging subsystem and then I will move over to this issue.

**Comment by mariodivece** [comment] 2018-09-18 01:42
I investigated this issue a little more and I see what the problem is: Priority commands such as play, pause and others, completely clear the queued seek commands. This makes sense. So I might need to create a new event OnMediaReady which is fired when the initial Pause or Play command has been executed and then the user can safely queue seek commands.

**Comment by woolersj** [comment] 2018-09-18 14:28
Thanks for the updates. Latest commit is much improved. 
I'm calling `await Media.Seek(target)` on the `MediaReady` event as you suggested.
I am however still seeing some inconsistency seeking to a target position.  It is only ever 1 frame out now **(videos at 25 fps)** and I only see the the problem during the first load of the application. Subsequent opening of the same video at the same position gives consistent results. 

On a side note as part of these updates you removed the **CurrentPosition** property which returned the discrete timestamp of the current frame. I was using this TimeSpan to pass to ffmpeg to implement _TakeSnapshot_ functionality that I use as a thumbnail for a position in a video.
**CurrentPosition** gave me more repeatable results than using the **Position** dependency property.

When the Position dependency property has been updated using StepForward or StepBackward (was PositionNext/Previous) calling **ffmpeg** to extract a frame always gave me the same frame as what is displayed in the player.
If the Position dependency property had been updated using the **slider**,  calling **ffmpeg** doesn't always give the same frame as displayed in the player.
Is there any way I can get the discrete timestamp of the current frame in the latest code. Does the new Neighbors functionality contain what I need?

Thanks in advance

**Comment by mariodivece** [comment] 2018-09-18 17:43
Hmmm... I think I will need to add a read-only property called 'FramePosition' to extract the exact discrete position as you suggest. 
On a different note, is there any reason why you are not hooking up to the RenderingVideo event? It has the bitmap buffer in there, exact timestamp, etc. in the event arguments....

**Comment by mariodivece** [comment] 2018-09-18 19:15
ok. I have added the `FramePosition` property which returns the timestamp of the current frame. 
I am a little lost now on what else you are reporting as there seems to be a handful of items so let's address one by one. So, number 1, please test with the `FramePosition` property and let me know the results. Next, describe the following item that you believe needs addressing.

**Comment by woolersj** [comment] 2018-09-19 15:01
Great Thanks. Inclusion of **FramePosition** property allows me to accurately extract a frame using ffmpeg. As far as I am concerned this issue can be closed.

**Comment by mariodivece** [comment] 2018-09-23 14:10
Ok good. Closing then! Thanks for the issue report and feedback!

**Closed by mariodivece** 2018-09-23 14:10 UTC
Labels: bug
