### ISSUE TITLE
Rounding weirdness when setting Media.Position?

### ISSUE THREAD

**Issue by flipswitchingmonkey** [unosquare/ffmediaelement#166] opened 2018-02-14 18:46 UTC
I'm seeking to a specific frame in a clip using a method like this:
```
        private void SeekToPosition(int newFrame)
        {
            double newPosition = (double)newFrame * Media.VideoFrameLength;
            SeekToPosition(TimeSpan.FromSeconds(newPosition));
        }

        private void SeekToPosition(double newPosition)
        {
            SeekToPosition(TimeSpan.FromSeconds(newPosition));
        }

        private void SeekToPosition(TimeSpan newPosition)
        {
            Media.Position = newPosition;
        }
```

It works - almost. Every now and then (I've not really found a rule for when it happens) the video is set to the frame before the one I'm looking for. I looked at the TimeSpans and noticed that in those cases they are off as well.
If I hardcode a slight offset like this
`            SeekToPosition(TimeSpan.FromSeconds(newPosition + 0.001));`
it seems to fix the problem. Could there be something somewhere that's rounding? Or maybe if a specific frame isn't hit entirely 100% based on the timecode in seconds, it decides to deliver the one before?

**Comment by mariodivece** [comment] 2018-02-16 04:26
is there any way you guys could provide some sample files? I know where the rounding is taking place and I might already know what the problem is.

**Comment by trigger-death** [comment] 2018-02-16 14:55
Sure try this.

[59 FPS.zip](https://github.com/unosquare/ffmediaelement/files/1731721/59.FPS.zip)

**Comment by mariodivece** [comment] 2018-02-17 23:46
Ok, could you guys check out my latest commit on branch rootvm
https://github.com/unosquare/ffmediaelement/tree/rootvm

I have removed the rounding calls (i.e. .Normalize()) to timestamps to prevent rounding to the nearest wholes millisecond. Please let me know the results. Thanks!

**Comment by trigger-death** [comment] 2018-02-20 16:14
Sorry it took me so long to get to testing this. I can confirm this isn't enough to solve the issue. The rounding most likely was a factor but it seems it's not enough to prevent the next from frame from not being navigated to.

**Comment by mariodivece** [comment] 2018-02-20 16:54
Could you send me steps to reproduce, current results and expected results?

**Comment by mariodivece** [comment] 2018-02-21 14:35
You have made several wrong assumptions. Here is the code that works. I am closing this issue.
Please consider a donation: https://www.paypal.me/mariodivece/50usd

```xaml
<Window x:Class="Unosquare.FFME.FrmaeStepping.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:Unosquare.FFME.FrmaeStepping"
        xmlns:ffme="clr-namespace:Unosquare.FFME;assembly=ffme.win"
        mc:Ignorable="d" Loaded="Window_Loaded"
        Title="MainWindow" Height="350" Width="525">
    <StackPanel>
        <ffme:MediaElement x:Name="Media" Width="160" Height="144" RenderingVideo="Media_RenderingVideo" />
        <Button Content="Frame++" Click="Button_Click"/>
        <Label x:Name="labelFrame" Content="Frame: 0"/>
        <Label x:Name="labelPictureNumber" Content="Picture Number: 0" />
    </StackPanel>
</Window>
```

```csharp
namespace Unosquare.FFME.FrmaeStepping
{
    using System;
    using System.Windows;

    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        private const string MediaSource = @"c:\users\UnoSp\Downloads\ReRecording2.avi";

        /// <summary>
        /// Initializes a new instance of the <see cref="MainWindow"/> class.
        /// </summary>
        public MainWindow()
        {
            // Default initialization
            InitializeComponent();

            // Setup ffmpeg
            Unosquare.FFME.MediaElement.FFmpegDirectory = @"C:\ffmpeg";
        }

        /// <summary>
        /// Handles the Loaded event of the Window control.
        /// This loads the Media Source
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">The <see cref="RoutedEventArgs"/> instance containing the event data.</param>
        private void Window_Loaded(object sender, RoutedEventArgs e) => 
            Media.Source = new Uri(MediaSource);

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            // Use Convert to automatically round
            var currentFrame = Convert.ToInt32(Media.Position.TotalSeconds * Media.VideoFrameRate);
            currentFrame++;

            // We add 1 millisecond because the CURRENT frame is from 0 to 59.xxx; the NEXT frame starts at GREATER than 59.xxx
            // Use VideoFrameLength to compute the new position as it is based on Ticks (not whole milliseconds)
            // Remember that if timespans are created from anything other than Ticks, these are rounded to the nearest WHOLE millisecond
            Media.Position = TimeSpan.FromSeconds(currentFrame * Media.VideoFrameLength + 0.001);

            // The incremented frame is all that will be reflected in this label.
            labelFrame.Content = $"Computed Frame Index: {currentFrame}";
        }

        /// <summary>
        /// Handles the RenderingVideo event of the Media control.
        /// Just showing a feture where you can extract the picture number (i.e. Frame Index + 1)
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">The <see cref="Events.RenderingVideoEventArgs"/> instance containing the event data.</param>
        private void Media_RenderingVideo(object sender, Events.RenderingVideoEventArgs e) => 
            labelPictureNumber.Content = $"Actual Picture Number: {e.PictureNumber}";
    }
}
```

**Closed by mariodivece** 2018-02-21 14:35 UTC
Labels: bug, question
