### ISSUE TITLE
Play audio file?

### ISSUE THREAD

**Issue by xupefei** [unosquare/ffmediaelement#27] opened 2017-05-22 18:41 UTC
Hello, thanks for making such a great control for WPF.

I have used this control in my own project however I find that when I try to load a audio file (like `a.mp3` and `b.ogg`), the control always gives `Duration=0` and `HasAudio=0`, and nothing happens when I try to play it.
Could you tell me if it *actually* support such audio format, or there is anything I go wrong?

**Comment by mariodivece** [comment] 2017-05-22 20:18
I am working on a much improved version right now. Could you provide the sample files so I can test and ensure they work with the new version? I should be done with the new one in a couple more weeks.

**Comment by xupefei** [comment] 2017-05-22 20:34
Thanks for the response.
Please find the attached archive for a sample MP3 and OGG files:
```
Input #0, mp3, from 'Finlandia_Hymn_chorus.mp3':
  Metadata:
Finlandia, Op. 26   :     nan    :  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0
    album           : Finlandia, Op. 26
    artist          : Jean Sibelius
    encoder         : Lavf57.72.101
  Duration: 00:02:10.39, start: 0.023021, bitrate: 129 kb/s
    Stream #0:0: Audio: mp3, 48000 Hz, stereo, s16p, 128 kb/s
    Metadata:
      encoder         : Lavc57.95
    Stream #0:1: Video: png, gray(pc), 395x252 [SAR 2835:2835 DAR 395:252], 90k tbr, 90k tbn, 90k tbc
    Metadata:
      comment         : Cover (front)
```

```
Input #0, ogg, from 'Finlandia_Hymn_chorus.ogg':
  Duration: 00:02:10.34, start: 0.000000, bitrate: 139 kb/s
    Stream #0:0: Audio: vorbis, 48000 Hz, stereo, fltp, 160 kb/s
    Metadata:
      ARTIST          : Jean Sibelius
      TITLE           : Finlandia, Op. 26
      ALBUM           : Finlandia, Op. 26
    Stream #0:1: Video: png, gray(pc), 395x252 [SAR 2835:2835 DAR 395:252], 90k tbr, 90k tbn, 90k tbc
    Metadata:
      comment         : Cover (front)
```

Please also note that they have cover arts embedded.

[Finlandia_samples.zip](https://github.com/unosquare/ffmediaelement/files/1020130/Finlandia_samples.zip)

**Comment by mariodivece** [comment] 2017-05-24 21:49
I can confirm these 2 files are rendered correctly with the new decoder core. Both the music and the cover art render well. These did reveal an issue with frame-exact seeking which I already know how to fix.

**Comment by mariodivece** [comment] 2017-06-13 17:12
Closing because the new core handles these without issues.

**Closed by mariodivece** 2017-06-13 17:12 UTC
Labels: bug
