### ISSUE TITLE
Audio filters not applied

### ISSUE THREAD

**Issue by jonrigz** [unosquare/ffmediaelement#302] opened 2018-12-02 21:58 UTC
# Audio filters not applied

Audio filter strings do not seem to be applied when handling the MediaOpening or MediaChanging events. Is this a bug or am I missing something? Tried with purposefully crude/obvious filters to test. Video filter is applied as expected. Applying the audio filter via ffplay command line works as expected.

When an intentional typo is added to the video filter a System.AccessViolationException is thrown, however this does not happen when doing the same thing in the audio filter.

Thanks for the fantastic project!

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x] Question
 - [ ] Not sure

## Version Information

 - [x] NuGet Package 4.0.270
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*
 
### XAML
```xml
<ffme:MediaElement x:Name="Media" 
                           Source="C:\TestFile.mxf"
                           LoadedBehavior="Manual" 
                           Background="Black"/>
```

### C#
```csharp
        public TestPage()
        {
            InitializeComponent();
            Media.MediaOpening += OnMediaChanging;
            Media.MediaChanging += OnMediaChanging;
        }

        private void OnMediaChanging(object sender, MediaOpeningEventArgs e)
        {
            e.Options.AudioFilter = "aphaser";
            e.Options.VideoFilter = "crop=100:100:12:34";
        }
```

### Command line ffplay
```batch
ffplay -af "aphaser" C:\TestFile.mxf
```

**Comment by mariodivece** [comment] 2019-01-28 14:39
I just checked and it works fine on both -- MediaChanging and MediaOpening events... I can't repro the issue. Could you try with the latest Master commit and let me know the results?

**Comment by mariodivece** [comment] 2019-02-16 02:46
Since there is no further feedback and the issue could not be reproduced, I am closing this.

**Closed by mariodivece** 2019-02-16 02:46 UTC
Labels: bug

**Comment by jonrigz** [comment] 2019-03-17 15:38
Hi Mario. Thanks very much for taking the time to look at this, and apologies for the lack of response, I've been travelling recently. I've run some more tests on this and the issue appears to be isolated to PCM audio. I've tried this in MXF, MOV, and MKV and get the same results with each, so doesn't appear to be affected by container format. Using AAC for example in a MOV or MKV works fine. Have tried this with the latest commit.

**Comment by mariodivece** [comment] 2019-03-17 15:39
a sample file would be useful...

**Comment by jonrigz** [comment] 2019-03-17 18:32
Have prepared some sample files here:
https://www.dropbox.com/sh/8tq2kco9yl5neef/AADRkSFiDaYx3GgBGNkEW8RKa?dl=0

Interestingly, it looks like my initial observation that this isn't affected by container format was incorrect. PCM in MOV appears to work fine regardless of channel configuration, whereas PCM in MXF and MKV results in the AF not being applied. Using ffplay command line the AF works with all of the files in the AF-FAIL folder.

These samples have all been produced with FFmpeg (with one re-wrapped using BBC BMX). I'll create some samples with other transcoders/muxers during the week to see if that makes any difference.

**Comment by mariodivece** [comment] 2019-03-18 03:50
is your test filter still "aphaser"?

**Comment by jonrigz** [comment] 2019-03-18 11:58
Yes, still testing with "aphaser".
