### ISSUE TITLE
Multiple instances: increased CPU and memory usage

### ISSUE THREAD

**Issue by KodeKooker** [unosquare/ffmediaelement#273] opened 2018-09-04 13:53 UTC
MediaElement multiple instances increased CPU & memory usage

As shown below, MediaElement resource usage increased since Michelob first releases. 

Michelob - 2.0.b1 version (WPF win10 o.s.)
10 MediaElements together (lowering worker threads priority) => process CPU usage 35/45%
Medium RAM usage = 1950 MB

Michelob - 2.60 version (WPF win10 o.s.)
10 MediaElements together (lowering worker threads priority) => process CPU usage 55/65%
Medium RAM usage = 2600 MB

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x] Question
 - [ ] Not sure

## Version Information

 - [ ] NuGet Package *Enter Version Number Here*
 - [x] Build From *Master* branch, Commit b75b06c
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

## Expected Results
Resource usage should be improved or at least left unchanged.
I had to keep using an older release in order to get low CPU/memory usage.

**Comment by mariodivece** [comment] 2018-09-09 18:08
Thereferenced commit is from June 3. Are you sure you are testing with the latest master branch commit? Could you please provide a sample or something I can more easily reproduce? A coupl eof projects would be useful. The latest master commit contains numerous improvements. I have a few test file and I am getting 20% to 40% less CPU usage than prior releases...

**Comment by KodeKooker** [comment] 2018-09-10 09:14
I am always testing the latest Release version (Michelob - 2.60, in this case) in order to avoid stability issues. Maybe the next Release will improve CPU / memory usage...

**Comment by mariodivece** [comment] 2018-09-17 23:48
Wait... you are saying that 2.60 has lower CPU usage and lower memory usage than the initial beta release... The usage is decreasing according to your reports... In any case, further CPU and memory improvements are coming to 2.70

**Comment by KodeKooker** [comment] 2018-09-19 10:31
I switched version numbers, now they're ok.

**Comment by mariodivece** [comment] 2018-09-24 03:45
Version 2.70 is now available via NuGet. Please share your results!

**Comment by mariodivece** [comment] 2019-02-18 07:16
Closing this one. There has been a lot of changes since then and no further comment. Feel free to share your results using the latest commit to Master.

**Closed by mariodivece** 2019-02-18 07:16 UTC
Labels: question
