### ISSUE TITLE
NDI Playback using libndi_newtek

### ISSUE THREAD

**Issue by Jelteh** [unosquare/ffmediaelement#315] opened 2019-01-22 18:49 UTC
# NDI Playback using libndi_newtek

Would it be possible to playback an NDI stream using a recompiled ffmpeg version with libndi_newtek enabled?
How can I pass this as the source of the mediaelement? (See ffplay command line below)

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x] Question
 - [ ] Not sure

## Version Information

 - [x] NuGet Package 'Latest'

### Command line ffplay

ffplay -f libndi_newtek -extra_ips "127.0.0.1" -i "MyComputerName (Test Pattern)"

**Comment by mariodivece** [comment] 2019-01-22 19:05
try the following:
`media.Source = $"device://libndi_newtek?{Uri.EscapeDataString("MyComputerName (Test Pattern)")}";`

and on MediaInitializing event:
`e.Configuration.PrivateOptions["extra_ips"] = "127.0.0.1";`

**Comment by mariodivece** [comment] 2019-01-22 20:45
Please let me know if this worked.

**Comment by Jelteh** [comment] 2019-01-24 11:21
Thanks! Setting the source and extra_ips works!

But... it only loads (and shows!) the first frame..

Message log:
`[19:19.122 | DBG | Engine.Commands     ] Open Entered
[19:19.332 | INF | Engine.Commands     ] FFInterop.Initialize: FFmpeg vN-92987-g399c8e860f
[19:19.333 | INF | Engine.Commands     ] Media URI will be updated. Input Format: libndi_newtek, Input Argument: LT-JELTE (Test Pattern)
[19:23.070 | DBG | Container.Component ] AUDIO: Start Offset: 1548328554,531; Duration:        N/A
[19:23.082 | DBG | Container.Component ] VIDEO: Start Offset:      0,000; Duration:        N/A
[19:23.085 | INF | Container           ] Timing Offsets - Main Component: Video; Start Time:      0,000; Duration:        N/A; 
[19:23.210 | DBG | Engine.Decoding     ] Decoder sync-buffering started.
[19:23.298 | DBG | Engine.Commands     ] Open Completed`

**Comment by mariodivece** [comment] 2019-01-31 02:52
let me look into this a little more closely... I will improve the sync-buffering logic (it's one of the main items). It would be nice if you got more familiar with the code and provided more information on what the problem might be since I do not own this type of hardware.

**Comment by jhonniedj** [comment] 2019-01-31 07:58
You dont need any extra hardware to get a NDI stream/test-pattern up and running.

I can simulate the same issue as Jelteh by installing the Newtek NDI SDK and using the Test Pattern.exe 
Then with ffmpeg (build with --enable-libndi_newtek --enable-nonfree package) you can capture the stream well with ffplay:
`ffplay -x 500 -f libndi_newtek -extra_ips "127.0.0.1" -i "YOURCOMPUTERNAMEHERE (Test Pattern)" `

But in FFMediaElement it will capture 1 frame, and then flipper with playing/stopping/buffering

**Comment by mariodivece** [comment] 2019-02-04 23:31
ok... I am currenlty implementing a new playback model. I will test this one as well.

**Comment by jhonniedj** [comment] 2019-02-11 08:31
> ok... I am currenlty implementing a new playback model. I will test this one as well.

Any updates on this point?

**Comment by mariodivece** [comment] 2019-02-11 14:33
Remember this is a hobby project of mine. If you need updates, you can check the commits in the1 or 2 branches I typically have. Just don't hold your breath.

**Comment by mariodivece** [comment] 2019-02-16 02:44
Just out of curiosity, could you please try using the latest commit under the better-workers-2 branch and let me know if it works now?

**Comment by Jelteh** [comment] 2019-02-22 16:43
Just tried it.. Again by running your example (Unoqsuare.FFME.Windows.Sample) and adding the Media.Source and MediaInitializing lines you proposed. NewTek NDI SDK installed and running TestPatterns. 

Unfortunality no results..

AudioRender.Read keeps getting a overflow exception and the player keeps starting/stopping..

**Comment by mariodivece** [comment] 2019-02-22 23:47
Could anyone provide an FFmpeg build with this NDI input format so I can test with the SDK?

**Comment by mariodivece** [comment] 2019-02-23 18:28
I give up. After 4 hours of compiling ffmpeg with the NDI includes (v3.8 SDK) it miserably fails with the following message:
![image](https://user-images.githubusercontent.com/351978/53290194-32347000-3766-11e9-92d1-ebc21fa00574.png)

Obviously the NDI dlls are on the same folder as ffmpeg. Looks like the SDK header files were changed and no longer match what avdevice is expecting.

**Comment by Jelteh** [comment] 2019-02-23 18:53
No problem.. ;) we've had some issues as well.. 

Where can I send you a private message? So we can share the files with you..

**Comment by mariodivece** [comment] 2019-02-23 20:34
send me an email. It's just my first name at unosquare.com

**Comment by jhonniedj** [comment] 2019-02-23 21:39
I send you the ffmpeg compiled files by mail

**Comment by mariodivece** [comment] 2019-02-24 00:53
Never got them. My first name is mario

**Comment by jhonniedj** [comment] 2019-02-24 01:03
maybe inside the spam folder? As far as I see I got the mail address right..

**Comment by mariodivece** [comment] 2019-02-24 01:34
Yeah found it. Thanks!

**Comment by mariodivece** [comment] 2019-02-24 02:49
ok, using your normal build here's some preliminary verification and testing

Create NDI sample stream calles Sample:
`ffmpeg -re -i "C:\Users\UnoSp\OneDrive\ffme-testsuite\video-standard-02.mp4" -f libndi_newtek -pix_fmt bgra Sample`

Playing Streams with `ffplay`

Play the stream

`ffplay -x 500 -f libndi_newtek -extra_ips "127.0.0.1" -i "HOME-SLIMBIRD (Sample)"`
Result: Sometimes it plays ok, sometimes it gets stuck

Play the Test Pattern Stream:
`ffplay -x 500 -f libndi_newtek -extra_ips "127.0.0.1" -i "HOME-SLIMBIRD (Test Pattern)"`
Result: Works

Moving on to testing with FFME will let you know the results.

**Comment by mariodivece** [comment] 2019-02-24 21:51
Update: This has forced me to rethink several things that I knew needed fixing but had not encountered edge cases. Making good progress. Here's what I am working on:
- Eliminate the offset measures for components when decoding PTS. Remove useless offsets in seeking logic
- Keep track of a frame serial number and render based on on it rather than PTS
- Rewrite the way Media Start Time, Media Duration and Media End Time are computed and expose them through IMediaEngineState so they become available to the control
- Add frame PTS generation logic when the decoder keeps getting the same PTS over and over again.
- Add an option to disable sync-buffering -- this will mean: render whatever becomes available

**Comment by jhonniedj** [comment] 2019-02-27 09:48
Marvellous! good to hear you got ffplay working and can reproduce the issue :)
Thanks in advance

**Comment by mariodivece** [comment] 2019-03-04 15:27
This should work fine now with the latest master. Please let me know your results so I can close.

**Comment by mariodivece** [comment] 2019-03-05 02:26
So, can I close this one off now?

**Comment by Jelteh** [comment] 2019-03-05 19:13
I just ran the test again, it is working well with NDI Test Patterns now! Awesome!

My goal is to display the output of vMix using NDI. I did another test by playing a video inside vMix and then opening the NDI output inside FFME.Sample. 

MyComputerName (vMix - Output 1) is now the 'uri'

Unfortunality the video has dropped frames/is not playing well inside FFME.. But it is playing well inside NDI Studio Monitor.
I just discovered it is not playing well inside FFPLAY either, it gets stuck or plays really slow. So I don't know if this means it is not fixable for you.. but on the other side your app is doing way better than FFPLAY.. so maybe you can run this test aswell?

I tried the FFMPEG command you posted, to stream directly from a videofile.. but for some reason the video is playing very slow.. 

Many thanks for all the effort you put into this! It's a great project and a lot of work you put into this 'hobby project'! Really awesome!

**Comment by mariodivece** [comment] 2019-03-06 01:19
In my latest commit, try e.Options.DropLateFrames = true; and e.Options.IsTimeSyncDisabled = true; Could you try it out and let me know the results?

**Comment by Jelteh** [comment] 2019-03-06 18:17
Yep that worked! Playback has improved significantly.. 

Unfortunality the latency has gained aswell..
Your build from yesterday has around 300ms delay between vMix and FFME.
The build from today has around 1000ms delay..

Compared to NDI Studio Monitor, which has around 150-200ms, it is quite a lot..

**Comment by mariodivece** [comment] 2019-03-11 16:58
Using the latest `master` commit, could you please test by handling the `MediaOpening` event and adjusting the following `Options` to your needs? Please let me know the results. If there are no further comments before the end of this week, I will package and publish the new NuGet and consider this issue closed.

```csharp
	// You can render audio and video as it becomes available but the downside of disabling time
	// synchronization is that video and audio will run on their own independent clocks.
	// Do not disable Time Sync for streams that need synchronized audio and video.
	e.Options.IsTimeSyncDisabled =
		e.Info.Format == "libndi_newtek" ||
		e.Info.InputUrl.StartsWith("rtsp://uno");

	// You can disable the requirement of buffering packets by setting the playback
	// buffer percent to 0. Values of less than 0.5 for live or network streams are not recommended.
	e.Options.MinimumPlaybackBufferPercent = e.Info.Format == "libndi_newtek" ? 0 : 0.5;

	// The audio renderer will try to keep the audio hardware synchronized
	// to the playback position by default.
	// A few WMV files I have tested don't have continuous enough audio packets to support
	// perfect synchronization between audio and video so we simply disable it.
	// Also if time synchronization is disabled, the recommendation is to also disable audio synchronization.
	Media.RendererOptions.AudioDisableSync =
		e.Options.IsTimeSyncDisabled ||
		e.Info.InputUrl.EndsWith(".wmv");
```

**Comment by Jelteh** [comment] 2019-03-14 09:26
Tried it, but could not make a difference..
Is it also possible to disable audio completely? In my case I don't actually need it..

Thanks again! And yes, it would be awesome when you can publish on NuGet, that makes it very easy for me to implement!

**Comment by mariodivece** [comment] 2019-03-14 12:46
Set the audiostream option to null

**Closed by mariodivece** 2019-03-14 12:46 UTC
Labels: question
