### ISSUE TITLE
Seeking audio-only streams hangs up

### ISSUE THREAD

**Issue by Alicg** [unosquare/ffmediaelement#380] opened 2019-04-25 12:30 UTC
# Seeking audio-only streams hangs up

When seeking to a random position in an audio-only stream FFME MediaPlayer hangs up.
As an input, I use a network audio stream from Youtube.

## Issue Categories

 - Bug

## Version Information

 - NuGet Package 4.1.300
 - Build From *Master* branch, Commit 363dbd6

### Following change in CommandManager.Seek.cs fixes the issue:
```csharp
private bool TrySignalBlocksAvailable(SeekMode mode, MediaType main, MediaBlockBuffer mainBlocks, TimeSpan targetPosition, bool hasSeekBlocks)
        {
            // signal that thesere is a main block available
            if (hasSeekBlocks == false && (main == MediaType.Video || /*the fix*/main == MediaType.Audio) && mainBlocks.IsInRange(targetPosition))
            {
```

**Comment by mariodivece** [comment] 2019-05-08 15:37
I am sorry I am unable to reproduce. Please provide the full URL. Does this also occur using the provided sample application?

**Comment by Alicg** [comment] 2019-05-10 09:06
I use [youtube-dl](https://ytdl-org.github.io/youtube-dl/download.html) to get separate video and audio stream urls from Youtube. For example:
`youtube-dl.exe -g https://www.youtube.com/watch?v=xo1VInw-SKc` 
Then I pass audio url to sample application. When I try to change the position sample application does nothing. If I apply the above fix, seeking starts to work properly.

**Comment by mariodivece** [comment] 2019-06-02 15:15
Should be fixed in the latest master commit. Please provide further feedback if needed.

**Closed by mariodivece** 2019-06-02 15:15 UTC
Labels: bug
