### ISSUE TITLE
How to get some statistics like VLC Media Player when play HLS stream

### ISSUE THREAD

**Issue by namcigar** [unosquare/ffmediaelement#336] opened 2019-03-14 09:36 UTC
# How to get some statistics like VLC Media Player when playing a HLS stream

I want to get some infos like this picture (VLC media player) when playing a HLS stream. How can I do it, thanks.

![question](https://user-images.githubusercontent.com/3125619/54346165-34a82c80-4677-11e9-866a-4e03b55a05ee.PNG)

## Issue Categories

 - [ ] Question

## Version Information

 - [ ] Build From *Master* branch

**Comment by mariodivece** [comment] 2019-03-14 12:50
Related to #138

**Comment by namcigar** [comment] 2019-03-15 03:22
Thank you, can't wait for it !

**Comment by mariodivece** [comment] 2019-03-31 17:55
duplicate of #138

**Closed by mariodivece** 2019-03-31 17:55 UTC
Labels: duplicate, enhancement
