### ISSUE TITLE
Source File is not released after the Close method is triggered

### ISSUE THREAD

**Issue by delpier** [unosquare/ffmediaelement#305] opened 2018-12-06 18:05 UTC
# Source File is not released after the Close method is triggered

I'm developing an application where I'm able to view some videos but in some occasions I can update the videos and while doing that the current videos are backup to a different folder
To do that I need to go to a different screen and I've a event that is raised when the view is invisible and triggers the method UnloadInternalVideoPlayerAsync

The issue is that while I'm doing the backup the file is not deleted and event If I try to manually delete the file is not possible because it is attached to a process

## Issue Categories

 - [ ] Bug
 - [ ] Not sure

## Version Information

 - [ ] NuGet Package *v4.0.30319*

## Steps to Reproduce

 1. Set a video to the source of the media element
 2. trigger the method MediaElement.Play()
 3. trigger the method MediaElement.Close()
 4. Try to delete the file

## Expected Results

 - After the MediaElement.Close, the file should be release from the MediaElement and could be deleted

### XAML
```xml
<ffme:MediaElement x:Name="Media" 
                   Background="White"
                   LoadedBehavior="Manual"
                   UnloadedBehavior="Play"
                   ScrubbingEnabled="True"
                   IsMuted="True"
                   Source="{Binding VideoPath, Converter={StaticResource PathToUriConverter}, Mode=TwoWay}"/>
```

### C#
```csharp
        private async Task UnloadInternalVideoPlayerAsync()
        {
            await Media.Stop();
            await Media.Close();

            // Force garbage collector to clear memory.
            GC.Collect();
            GC.WaitForPendingFinalizers();          
        }
```

**Comment by mariodivece** [comment] 2019-01-21 14:58
On the reference player, I place a media file on my desktop, open it, close it and while the application is still running, I can successfully delete the file without any issues. In other words, I cannot reproduce the issue you describe. Please comment again if you have further info so I can reopen.

**Closed by mariodivece** 2019-01-21 14:58 UTC
Labels: bug, invalid
