### ISSUE TITLE
Support Initializing MediaElement on a different thread ?

### ISSUE THREAD

**Issue by yangbocheng** [unosquare/ffmediaelement#384] opened 2019-04-30 07:39 UTC
# support init Mediaelement in Other Thread?
We often initialize a new Media Window with a New STA Thread.
But the current Version 2019.4.30 not  support it

## Issue Categories
 - [ ] enhancement

## Sugguest
 i have tried to make a temp little change, and it seems to run well. I am not sure if it would make bugs.
 An official support for it is maybe better.
 - [ ] AudioRender.cs #2 events +-
//Library.GuiContext.EnqueueInvoke(() =>Application.Current.Exit += OnApplicationExit);
Library.GuiContext.EnqueueInvoke(() => {
                    Application.Current.Dispatcher.Invoke(() =>
                    {
                        Application.Current.Exit += OnApplicationExit;
                    });
                });
 - [ ] GuiContext.cs
//cancel GuiDispatcher = Application.Current.Dispatcher

**Comment by mariodivece** [comment] 2019-05-08 15:21
could you provide sample code on how to reproduce the issue and error information? It's very hard to troubleshoot an issue like this if I can't reproduce it. Thanks in advance!

**Comment by mariodivece** [comment] 2019-06-02 15:05
It should work fine now. Could you try using a build from the latest master commit?

**Comment by yangbocheng** [comment] 2019-06-11 07:31
Thanks very much for your this excellent project. 
I am sorry for so late because of a holiday. Now i build project from the latest master commit today.

I need to explain: This issue is under this simple circumstance:
1.open a new normal project and so it would start with a MainWindow.
2.create a new STA Thread to build a new UI dispatcher Thread and show after a button-click. Like this below:
Winow window=null;
Thread th=new Thread(()=>
{
  window = new MediaPlayWindow3();
  window.Closed += (o, b) => Dispatcher.ExitAllFrames();
  Dispatcher.Run();
})
th.SetApartmentState(ApartmentState.STA);
To support it , so i hide this code like:GuiDispatcher = Application.Current.Dispatcher to avoid UIthread exception. And then it can run correctly.

But actually this way can make some other big problems. So i have to give up it:
After use stop() play() pause() randomly ,and play for over 20 seconds(need loop), There maybe often a strange unkown exception which can't be catched by DispatcherUnhandledException and AppDomain and TaskScheduler.
that's: 【 Exception thrown at 0x510424DA (dsound.dll) in TestWpf.exe: 0xC0000005: Access violation reading location 0xFFFFFFFF.】


Test tips:
#need set project properties-Debug- "Enable native code debugging" or it just would directly shutdown your exe
#use Any Cpu mode to complie; When it is built in x86, it's easier to reproduce this. That means it can produce int x64 either.


With new code bulid from lastest master commit and I create MeidaWindow in the Main UI Thread now instead of building window in a another thread above, And only use play() pause() stop() open() just like what it is in Sample project.
it can always work well after test for 2 hours

**Comment by yangbocheng** [comment] 2019-06-11 07:37
Thanks very much for your this excellent project. 
I am sorry for so late because of a holiday. Now i build project from the latest master commit today.
-----------------------------------------------------
I need to explain: This issue is under this simple circumstance:
1.open a new normal project and so it would start with a MainWindow.
2.create a new STA Thread to build a new UI dispatcher Thread and show after a button-click. Like this below:
Winow window=null;
Thread th=new Thread(()=>
{
  window = new MediaPlayWindow3();
  window.Closed += (o, b) => Dispatcher.ExitAllFrames();
  Dispatcher.Run();
})
th.SetApartmentState(ApartmentState.STA);
To support it , so i hide this code like:GuiDispatcher = Application.Current.Dispatcher to avoid UIthread exception. And then it can run correctly.

But actually this way can make some other big problems. So i have to give up it:
After use stop() play() pause() randomly ,and play for over 20 seconds(need loop), There maybe often a strange unkown exception which can't be catched by DispatcherUnhandledException and AppDomain and TaskScheduler.
that's: 【 Exception thrown at 0x510424DA (dsound.dll) in TestWpf.exe: 0xC0000005: Access violation reading location 0xFFFFFFFF.】

Test tips:
#need set project properties-Debug- "Enable native code debugging" or it just would directly shutdown your exe
#use Any Cpu mode to complie; When it is built in x86, it's easier to reproduce this. That means it can produce int x64 either.
-----------------------------------------------------
So I don't use a new thread to make it now. The exception above still exsit in the lastest commit.
With new code bulid from lastest master commit and I create MeidaWindow in the Main UI Thread now instead of building window in a another thread above, And only use play() pause() stop() open() just like what it is in Sample project.
then it can always work well after test for 2 hours

**Comment by yangbocheng** [comment] 2019-06-11 07:38
Thanks very much for your this excellent project. 
I am sorry for so late because of a holiday. Now i build project from the latest master commit today.
============================================================
I need to explain: This issue is under this simple circumstance:
1.open a new normal project and so it would start with a MainWindow.
2.create a new STA Thread to build a new UI dispatcher Thread and show after a button-click. Like this below:
Winow window=null;
Thread th=new Thread(()=>
{
  window = new MediaPlayWindow3();
  window.Closed += (o, b) => Dispatcher.ExitAllFrames();
  Dispatcher.Run();
})
th.SetApartmentState(ApartmentState.STA);
To support it , so i hide this code like:GuiDispatcher = Application.Current.Dispatcher to avoid UIthread exception. And then it can run correctly.

But actually this way can make some other big problems. So i have to give up it:
After use stop() play() pause() randomly ,and play for over 20 seconds(need loop), There maybe often a strange unkown exception which can't be catched by DispatcherUnhandledException and AppDomain and TaskScheduler.
that's: 【 Exception thrown at 0x510424DA (dsound.dll) in TestWpf.exe: 0xC0000005: Access violation reading location 0xFFFFFFFF.】

Test tips:
#need set project properties-Debug- "Enable native code debugging" or it just would directly shutdown your exe
#use Any Cpu mode to complie; When it is built in x86, it's easier to reproduce this. That means it can produce int x64 either.
============================================================
So I don't use a new thread to make it now. The exception above still exsit in the lastest commit.
With new code bulid from lastest master commit and I create MeidaWindow in the Main UI Thread now instead of building window in a another thread above, And only use play() pause() stop() open() just like what it is in Sample project.
then it can always work well after test for 2 hours

**Comment by yangbocheng** [comment] 2019-06-11 07:39
Thanks very much for your this excellent project. 
I am sorry for so late because of a holiday. Now i build project from the latest master commit today.

I need to explain: This issue is under this simple circumstance:

1.open a new normal project and so it would start with a MainWindow.
2.create a new STA Thread to build a new UI dispatcher Thread and show after a button-click. Like this below:
Winow window=null;
Thread th=new Thread(()=>
{
  window = new MediaPlayWindow3();
  window.Closed += (o, b) => Dispatcher.ExitAllFrames();
  Dispatcher.Run();
})
th.SetApartmentState(ApartmentState.STA);
To support it , so i hide this code like:GuiDispatcher = Application.Current.Dispatcher to avoid UIthread exception. And then it can run correctly.

But actually this way can make some other big problems. So i have to give up it:
After use stop() play() pause() randomly ,and play for over 20 seconds(need loop), There maybe often a strange unkown exception which can't be catched by DispatcherUnhandledException and AppDomain and TaskScheduler.
that's: 【 Exception thrown at 0x510424DA (dsound.dll) in TestWpf.exe: 0xC0000005: Access violation reading location 0xFFFFFFFF.】

above Test tips:
#need set project properties-Debug- "Enable native code debugging" or it just would directly shutdown your exe
#use Any Cpu mode to complie; When it is built in x86, it's easier to reproduce this. That means it can produce int x64 either.

So I don't use a new thread to make it now. The exception above still exsit in the lastest commit.
With new code bulid from lastest master commit and I create MeidaWindow in the Main UI Thread now instead of building window in a another thread above, And only use play() pause() stop() open() just like what it is in Sample project.
then it can always work well after test for 2 hours

**Comment by mariodivece** [comment] 2019-06-29 17:15
have you tried using 
`media.RendererOptions.UseLegacyAudioOut = true`
dsound.dll has given issues to some users... any chance you can get me the stack trace of that exception?

**Comment by mariodivece** [comment] 2019-12-06 23:23
Closing this one. The dsound issue will be continued on #388

**Closed by mariodivece** 2019-12-06 23:23 UTC
Labels: enhancement
