### ISSUE TITLE
Growing delay in RTSP stream

### ISSUE THREAD

**Issue by vakym** [unosquare/ffmediaelement#212] opened 2018-04-19 12:55 UTC
#Growing delay in RTSP stream

Hi, first of all thank you for this project.
I use it for displaying RTSP streams from cameras.
At stream start everything works normally, but in some minutes(5-6) the delay begins to grow. 

I set nex options:
```
private void OnMediaInitializing(object sender, MediaInitializingRoutedEventArgs e)
 {
     e.Options.Input["rtsp_transport"] = "tcp";
     e.Options.Format.FlagNoBuffer = true;
     e.Options.Format.ProbeSize = 40000;  
     e.Options.Format.MaxAnalyzeDuration = System.TimeSpan.Zero;
}

private void OnMediaOpening(object sender, MediaOpeningRoutedEventArgs e)
{
               e.Options.EnableLowDelay = true;
                e.Options.EnableFastDecoding = true;
                e.Options.EnableHardwareAcceleration = true;
                e.Options.EnableLowRes = true;
}
```
Why it's happen?

P.s
What mean parametr   e.Options.Format.ProbeSize? Where can i read about it? If i set it below 10000 then i see many horizontal lines on video picture.

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x] Question
 - [ ] Not sure

## Version Information

 - [ ] NuGet Package *Enter Version Number Here*
 - [x] Build From *Master* branch, Commit *a205ce3*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

**Comment by mariodivece** [comment] 2018-04-19 17:42
This is typically caused by a mismatch in automatic FPS detection and the FPS the stream actually holds. Couple of questions:
1. what is the full command-line to ffplay.exe that gets you the desired effect?
2. If you don't add the no-buffering settings as you are currently doing, do you still experience the growing delays?

**Comment by vakym** [comment] 2018-04-20 10:17
1. I get good result with:
`ffplay.exe -flags low_delay  -rtsp_transport tcp  -i rtsp://192.168.1.232/rtsp_tunnel?line=3  -vf "yadif=0:0,fps=30"`
Delay is some 0.5-1 second. 
But i'm note sure about `fps` flag. Looks like it ignored, because in command line i see this:
`Stream #0:0: Video: h264 (Main), yuv420p(top first), 704x576 [SAR 12:11 DAR 4:3],` **25 fps** `, 25 tbr, 90k tbn, 50 tbc
  14.09 M-V:  0.026 fd=   2 aq=    0KB vq=  181KB sq=    0B f=0/1`

2. If i don't add the no-buffering settings, the delay still growing up, but more slower.
`e.Options.Format.FlagNoBuffer = false;`

How can i set flags(-vf) from my command in code?

**Comment by vakym** [comment] 2018-04-23 07:59
Update.
I tested command
`ffplay.exe -flags low_delay -rtsp_transport tcp -i rtsp://192.168.1.232/rtsp_tunnel?line=3 -vf "yadif=0:0,fps=30"` on long distanse(all weekend) and it works fine. The `fps` flag not ignored. The delay not growing.
Please, tell me how i can configure the same parametrs in code?

**Comment by vakym** [comment] 2018-04-23 09:42
Looks like i solve this question.
1)I added new property in `MediaOptions.cs`:
` public int? FPS { get; set; } = null;`
2) Change constructor of MediaComponent in line 86.
Before:
`ffmpeg.av_codec_set_pkt_timebase(CodecContext, Stream->time_base);`
After:
```
if (Container.MediaOptions.FPS == null)
  {
    ffmpeg.av_codec_set_pkt_timebase(CodecContext, Stream->time_base);
  }
  else
  {
    ffmpeg.av_codec_set_pkt_timebase(CodecContext, new AVRational { num = 1, den = Convert.ToInt32(Container.MediaOptions.FPS) });
  }
```

3) In Smaple project, in MainWindow.MediaEvents.cs.
Set the FPS property int   OnMediaOpening() event. 
```
 private void OnMediaOpening(object sender, MediaOpeningRoutedEventArgs e)
        {
          e.Options.FPS = 30;
        }
```

I'm not sure that's a good answer. Can you comment on that?

**Comment by mariodivece** [comment] 2018-04-23 09:54
Seems like an excellent addition to the options object! Is this working well for you? If so I can me this the last change of the current milestone and release a new nugget package. Let me know.

**Comment by vakym** [comment] 2018-04-23 10:43
Sorry, i tested it again and it's not working=(
My problem is really in the fps mismatch because using ffplay.exe with the right parameters gives a good result. But I do not yet understand how to specify these parameters in the code.

**Comment by mariodivece** [comment] 2018-04-23 10:45
Tale a look at the c code in ffplay.c

**Comment by vakym** [comment] 2018-04-23 12:45
So, now i hope it will be work. 
Update step 2) in my previos comment.
```
if(Container.MediaOptions.FPS == null)
            {
                ffmpeg.av_codec_set_pkt_timebase(CodecContext, Stream->time_base);
            }
            else
            {
                AVRational fps = new AVRational { num = Convert.ToInt32(Container.MediaOptions.FPS), den = 1 };
                ffmpeg.av_codec_set_pkt_timebase(CodecContext, fps);
                ffmpeg.av_stream_set_r_frame_rate(Stream, fps);
            }
```

I tested it. Now in file/stream information we see correct(seted) fps value. In 40 min test i not see growing  delay. I will test it more, but i think it works.

**Comment by mariodivece** [comment] 2018-04-23 18:52
Could you test with my latest commit? The property is now called MediaOptions.ForcedVideoFps and it is a rationale so that more precise tamebases can be specified. 
https://github.com/unosquare/ffmediaelement/commit/2f3b5ccc8b80e0caa2dd002a082e734be0e1591a
Please close this issue if it works now. Example:

```csharp
            // You can force video FPS if necessary
            // see: https://github.com/unosquare/ffmediaelement/issues/212
            e.Options.VideoForcedFps = new AVRational { num = 25, den = 1 };
```

**Comment by mariodivece** [comment] 2018-04-24 18:07
Did you get a chance to check so I can release?

**Comment by vakym** [comment] 2018-04-24 18:12
Sorry, i'm not check it today. I do this.dialogresult tomorrow.

**Comment by mariodivece** [comment] 2018-04-25 13:41
Closing for 2.40 release. Reopen if required.

**Closed by mariodivece** 2018-04-25 13:41 UTC
Labels: enhancement, question
